spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Swami1472@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 9090

